[General]
autoMuteMic=false
autoTurnOffVideo=false
language=en-US
localRecordingPath=/home/user/Documents/Zoom
autoStart=false
HowlingDetection=true
Theme=1

[Audio]
AudioDevice=default
MicrophoneLevel=50
SpeakerLevel=50

[Video]
HDVideo=false
mirrorMyVideo=true
TouchUpMyAppearance=true

[chat.client]
Theme=light
