[General]
autoMuteMic=false
autoTurnOffVideo=false
language=en-US
localRecordingPath=/home/user/Documents/Zoom
autoStart=true
HowlingDetection=true
Theme=1

[Audio]
AudioDevice=default
MicrophoneLevel=50
SpeakerLevel=50
SuppressBackgroundNoise=2
EnableOriginalSound=false

[Video]
HDVideo=false
mirrorMyVideo=true
VideoDevice=Integrated Webcam
TouchUpMyAppearance=true

[chat.client]
Theme=light
EnableSpellCheck=true

[General.Meetings]
ShowTimer=true
ConfirmLeaveMeeting=true

